### ISSUE TITLE
"A streaming error has occured (WOW51900322)" When scanning the AH first time

### ISSUE THREAD

**Issue by c11epm** [mooreatv/AuctionDB#23] opened 2019-09-09 17:30 UTC
Hi,
Just installed the addon together with BVP, but when I start the first AH scan it starts for 3 seconds then I gets kicked out to main menu with the error in the title.
Am I missing something really silly? 
I have these addons installed:
* AHDB - latest version
* BVP - latest version
* Questie

**Comment by mooreatv** [comment] 2019-09-09 20:27
There are a handful of reports but nothing I've reproduced so far

Which Realm and Faction? do you have a fast network?

Also if you reconnect and rescan, does it work the 2nd time?

**Comment by c11epm** [comment] 2019-09-09 20:45
Playing Night Elf Hunter on Zandalar Tribe EU, fast internet... 500Mbit up/down
No it never works, it fails all the time after aprox. 3 sec and i get kicked out with the error message showing.
If it matters I play WoW under Lutris on an Ubuntu 19.04 install.
Addons installed by extracting the zip archives and moved into the Addons folder in the game install folder.

**Comment by mooreatv** [comment] 2019-09-09 21:42
Try lowering the show new items to None or 5
hmm maybe the virtualization makes wow slow and unable to catch up

**Comment by c11epm** [comment] 2019-09-10 07:37
Thanks for the reply, will test it tonight.

**Comment by mooreatv** [comment] 2019-09-10 19:34
glad to hear but I will try to make some slow down configurable, maybe hit you up to test when I have it done

**Comment by Woolba** [comment] 2019-09-14 12:54
I'm also getting this issue. Lowering the show new items slider to 0 doesn't make a difference to me. I still crash with the same error as the original post (WOW51900322).

Also running WoW via Wine on Fedora 30.

**Comment by Woolba** [comment] 2019-09-17 06:50
I just tried scanning again today and it scanned without a hitch with the default settings. Not sure what was happening the other day.

**Comment by c11epm** [comment] 2019-09-21 13:11
So for two days now this has happended again every time I scan AH. The debug prints of Scanned Items: XXXX/YYYYY happens one or two times usually around 7000/25000-ish items scanned before disconnected with the streaming error.
Could I do something about this, or is there another addon that can show AH prices for items in the backpack?
Cheers,

**Comment by Woolba** [comment] 2019-09-22 02:44
Initially after the new update was released (1.00.01) I was still getting disconnected on every scan. However last night and this morning I have been mostly fine. It seems to be dc'ing less for me, at least.

For reference, I'm on the Yojamba OCE classic server, Horde.

**Comment by mooreatv** [comment] 2019-09-22 09:25
if someone manage to get DCs in a reproducible manner and please get my attention on discord when you do so we can troubleshoot solutions

**Comment by mooreatv** [comment] 2019-09-29 01:15
going to close this until someone comes up with repro with the latest version of AHDB

**Closed by mooreatv** 2019-09-29 01:15 UTC
